# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Basics
locale: "en-US"
timezone: Europe/Rome

title: Coder Notes
subtitle: "A useless and unstructured collection of random notes, code and rants"
description: # let me think about it

name: "Carlo Casta"
email: carlo.casta@gmail.com

url: "https://carcass82.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"

twitter:
  username: carcass_82

github:
  username: carcass82

analytics:
  provider: "google"
  google:
    tracking_id: UA-156246734-1

comments:
  provider: "disqus"
  disqus:
    shortname: codernotes-github
    
atom_feed:
  path:
  
author:
  name: "Carlo Casta"
  avatar: "/img/avatar.jpg"
  bio: _Your friendly gfx programmer._
  location: "Milan, Italy"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/carcass_82"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/carcass82"
    - label: "email"
      icon: "fas fa-fw fa-at"
      url: "mailto:carlo.casta@gmail.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/carcass_82"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/carcass82"

# theme settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-paginate

tag_archive:
  type: liquid
  path: /tags/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
